---
name: release

on:
 push:
   branches:
     - "main"
 workflow_dispatch:
 
jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build binaries
        run: |
            CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -mod=vendor -ldflags="-s -w" -a -o build/terraform-provider-stripe-darwin-amd64
            CGO_ENABLED=0 GOOS=linux  GOARCH=386   go build -mod=vendor -ldflags="-s -w" -a -o build/terraform-provider-stripe-linux-386
            CGO_ENABLED=0 GOOS=linux  GOARCH=amd64 go build -mod=vendor -ldflags="-s -w" -a -o build/terraform-provider-stripe-linux-amd64
            CGO_ENABLED=0 GOOS=linux  GOARCH=arm   go build -mod=vendor -ldflags="-s -w" -a -o build/terraform-provider-stripe-linux-arm

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 'latest'
          tag: 'latest'
          commit: 'main'
          replacesArtifacts: true
          allowUpdates: true
          artifacts: "build/terraform-provider-stripe*"
          artifactErrorsFailBuild: false
          artifactContentType: 'application/octet-stream'
